pipeline:

  backend-1:
    image: golang
    group: build
    commands:
      - echo "sleep 10"
      - sleep 10
      
  test-1:
    image: golang
    group: build
    commands:
      - echo "test other"
      - touch a.txt
      - ls
      
  test-2:
    image: mhart/alpine-node:9.1.0
    group: testing
    secrets:
      - source: test
        target: test46
    commands:
      # - sleep 5
      # - yarn install
      - echo $TEST
      - echo $TEST46
      # - node redis.js
