pipeline:

  backend-1:
    image: golang
    group: build
    commands:
      - echo "sleep 10"
      - sleep 10
      
  test-1:
    image: mhart/alpine-node:9.1.0
    group: testing
    secrets: 
      -source: test
       target: man
       
      -source: test46
       target:woman
    commands:
      - echo "Print var"
      - echo $MAN
      - echo $WOMAN
      
#  test-2:
#    image: mhart/alpine-node:9.1.0
#    group: testing
#    secrets: [ test46, test ]
#    commands:
#      - echo "Print var"
#      - echo $TEST
#      - echo $TEST46
